org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_mappings_version=[VERSIONED]
parchment_mappings_mc_version=[VERSIONED]
minecraft_version_range=[VERSIONED]
neo_version=[VERSIONED]
loader_version_range=[1,)
mod_id=sensible_stackables
mod_name=Sensible Stackables
mod_license=MIT
mod_version=2.0.1
mod_group_id=me.pajic.sensible_stackables
mod_authors=pajic
mod_description=Change stack sizes for any item, with sensible defaults