org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=sensible_stackables
mod.name=Sensible Stackables
mod.group=me.pajic
mod.version=2.1.3
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Change stack sizes for any item, with sensible defaults
mod.sources_url=https://github.com/pajicadvance/sensible-stackables
mod.homepage_url=https://modrinth.com/mod/sensible-stackables
mod.issues_url=https://github.com/pajicadvance/sensible-stackables/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=5lQcMjaC
publish.curseforge=1178081
publish.github=false
